export const mockSchemes = [
  {
    id: "1",
    title: "PM Kisan Samman Nidhi",
    description: "Direct income support for farmers",
    category: "Agriculture",
    location: "All India",
    ageMin: 18,
    ageMax: 100,
    benefits: "₹6,000 per year in three equal installments",
    fullDescription:
      "The Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) is a central sector scheme that provides income support to all landholding farmers' families across the country, to supplement their financial needs for procuring various inputs related to agriculture and allied activities as well as domestic needs.",
    eligibilityCriteria: [
      "Must be a farmer with cultivable land",
      "Age between 18-100 years",
      "Valid Aadhaar card",
      "Bank account linked with Aadhaar",
    ],
    requiredDocuments: [
      "Aadhaar Card",
      "Land ownership documents",
      "Bank passbook",
      "Passport size photograph",
    ],
    instructions: [
      "Visit the official PM-KISAN portal",
      "Register using Aadhaar number",
      "Fill in land details",
      "Submit required documents",
      "Track application status online",
    ],
    isEligible: true,
  },
  {
    id: "2",
    title: "National Scholarship Portal - Post Matric",
    description: "Financial assistance for SC/ST/OBC students",
    category: "Education",
    location: "All India",
    ageMin: 18,
    ageMax: 25,
    benefits: "Up to ₹20,000 per year for college education",
    fullDescription:
      "The Post Matric Scholarship scheme provides financial assistance to students from SC/ST/OBC categories pursuing higher education to help them complete their studies without financial burden.",
    eligibilityCriteria: [
      "Must be SC/ST/OBC category student",
      "Age between 18-25 years",
      "Enrolled in recognized institution",
      "Family income less than ₹2.5 lakhs per annum",
    ],
    requiredDocuments: [
      "Category certificate",
      "Income certificate",
      "Previous year marksheet",
      "Current enrollment proof",
      "Bank details",
      "Aadhaar card",
    ],
    instructions: [
      "Register on National Scholarship Portal",
      "Fill application form carefully",
      "Upload all required documents",
      "Submit to institution for verification",
      "Track status on portal",
    ],
    deadline: "2025-12-31",
    isEligible: false,
    ineligibilityReason: "Your age (28) is outside the required 18-25 range.",
  },
  {
    id: "3",
    title: "Pradhan Mantri Awas Yojana - Urban",
    description: "Housing for all in urban areas",
    category: "Housing",
    location: "Urban Areas",
    ageMin: 21,
    ageMax: 70,
    benefits: "Subsidy up to ₹2.67 lakhs on home loans",
    fullDescription:
      "PMAY-U aims to provide affordable housing to all eligible beneficiaries in urban areas through financial assistance and interest subsidies on home loans.",
    eligibilityCriteria: [
      "Must not own a pucca house in India",
      "Age between 21-70 years",
      "Annual household income criteria varies by category",
      "First-time home buyer",
    ],
    requiredDocuments: [
      "Income certificate",
      "Aadhaar card",
      "Property documents",
      "Bank statements",
      "NOC from local authority",
    ],
    instructions: [
      "Visit PMAY official portal",
      "Check eligibility",
      "Apply through lending institution",
      "Submit documents for verification",
      "Get subsidy credited post approval",
    ],
    deadline: "2025-06-30",
    isEligible: true,
  },
  {
    id: "4",
    title: "Ayushman Bharat - PM-JAY",
    description: "Health insurance for economically vulnerable families",
    category: "Healthcare",
    location: "All India",
    ageMin: 0,
    ageMax: 100,
    benefits:
      "₹5 lakhs per family per year for secondary and tertiary care hospitalization",
    fullDescription:
      "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana (AB PM-JAY) is the world's largest health insurance scheme providing coverage to over 50 crore beneficiaries for healthcare.",
    eligibilityCriteria: [
      "Family listed in SECC 2011 database",
      "Belongs to identified vulnerable categories",
      "No age limit - covers entire family",
    ],
    requiredDocuments: [
      "Ration card",
      "Aadhaar card of all family members",
      "SECC verification documents",
    ],
    instructions: [
      "Check eligibility on official website",
      "Visit nearest Common Service Center",
      "Get Ayushman card printed",
      "Use at empaneled hospitals",
      "No payment needed at hospital",
    ],
    isEligible: true,
  },
  {
    id: "5",
    title: "Pradhan Mantri Mudra Yojana",
    description: "Loans for micro and small enterprises",
    category: "Entrepreneurship",
    location: "All India",
    ageMin: 18,
    ageMax: 65,
    benefits: "Loans up to ₹10 lakhs without collateral",
    fullDescription:
      "MUDRA (Micro Units Development and Refinance Agency) provides funding to non-corporate, non-farm small/micro enterprises through various lending institutions.",
    eligibilityCriteria: [
      "Age between 18-65 years",
      "Valid business plan",
      "No default history",
      "Indian citizen",
    ],
    requiredDocuments: [
      "Business plan",
      "Identity proof",
      "Address proof",
      "Bank statements",
      "Business registration (if any)",
    ],
    instructions: [
      "Prepare detailed business plan",
      "Visit nearest bank/NBFC",
      "Fill loan application",
      "Submit required documents",
      "Attend bank interview if required",
    ],
    deadline: "2025-12-31",
    isEligible: true,
  },
  {
    id: "6",
    title: "Skill India - PMKVY",
    description: "Free skill training and certification",
    category: "Skill Development",
    location: "All India",
    ageMin: 18,
    ageMax: 45,
    benefits:
      "Free skill training, assessment, and certification with monetary rewards",
    fullDescription:
      "Pradhan Mantri Kaushal Vikas Yojana (PMKVY) is the flagship scheme for skill training of youth. It aims to enable Indian youth to take up industry-relevant skill training.",
    eligibilityCriteria: [
      "Age between 18-45 years",
      "Indian citizen",
      "Unemployed or school/college dropout",
      "Basic education preferred",
    ],
    requiredDocuments: [
      "Aadhaar card",
      "Educational certificates",
      "Bank account details",
      "Passport size photograph",
    ],
    instructions: [
      "Visit Skill India portal",
      "Find training center near you",
      "Register for desired course",
      "Complete training",
      "Appear for assessment",
      "Receive certificate and reward",
    ],
    isEligible: false,
    ineligibilityReason: "Your age exceeds the maximum limit of 45 years.",
  },
];

export const mockNotifications = [
  {
    id: "1",
    type: "new_scheme",
    title: "New Scheme Available",
    message:
      "PM Digital India Scheme is now open for applications. Check your eligibility now!",
    timestamp: "2 hours ago",
    read: false,
  },
  {
    id: "2",
    type: "deadline",
    title: "Deadline Approaching",
    message: "National Scholarship Portal deadline is in 5 days. Apply now!",
    timestamp: "1 day ago",
    read: false,
  },
  {
    id: "3",
    type: "update",
    title: "Application Status Update",
    message:
      "Your PM Kisan application has been approved. Amount will be credited soon.",
    timestamp: "3 days ago",
    read: true,
  },
];

export const defaultUserProfile = {
  personalDetails: {
    fullName: "",
    dateOfBirth: "",
    gender: "",
    category: "",
    aadhaar: "",
    pan: "",
  },
  contactInfo: {
    mobile: "",
    email: "",
    address: "",
    city: "",
    state: "",
    pincode: "",
  },
  familyIncome: {
    fatherName: "",
    motherName: "",
    annualIncome: "",
    familySize: "",
    rationCardType: "",
  },
  educationEmployment: {
    education: "",
    occupation: "",
    employmentStatus: "",
  },
  bankDetails: {
    accountNumber: "",
    ifscCode: "",
    bankName: "",
    branchName: "",
  },
};
